[mgr]
ratio          = [3, 4, 5]
scrolloff      = 10
sort_by        = "alphabetical"
sort_dir_first = true
sort_sensitive = true

[[open.prepend_rules]]
url = "*/"
use = "dir"

[[open.prepend_rules]]
url = "*.pdf"
use = "view"

[[opener.dir]]
desc   = "Open project in Codium"
run    = "codium %S"
orphan = true

[[opener.edit]]
desc  = "Edit file with default editor"
run   = "hx %s"
block = true

[[opener.edit]]
desc   = "Edit file with TextEdit"
run    = "open -a TextEdit %s"
orphan = true

[[opener.play]]
desc   = "Play media using Apple Music"
run    = "open -a Music %s"
orphan = true

[[opener.play]]
desc   = "Play media using IINA"
run    = "iina %s"
orphan = true

[[opener.play]]
desc   = "Play media using MPV"
run    = "mpv %s"
orphan = true

[[opener.play]]
desc   = "Play music using IINA"
run    = "iina --music-mode %s"
orphan = true

[[opener.view]]
desc   = "View PDF file in Preview"
run    = "open -a Preview %s"
orphan = true

[[opener.view]]
desc   = "View PDF file in Skim"
run    = "open -a Skim %s"
orphan = true

[preview]
max_height = 800
max_width  = 800
tab_size   = 2
wrap       = "yes"
