[mgr]
ratio = [3, 4, 5]
scrolloff = 10
sort_by = "alphabetical"
sort_dir_first = true
sort_sensitive = true

[[open.prepend_rules]]
url = "*/"
use = "dir"

[[open.prepend_rules]]
url = "*.pdf"
use = "view"

[[opener.dir]]
block = false
desc = "Open project in Codium"
orphan = true
run = "codium %S"

[[opener.edit]]
block = true
desc = "Edit file with default editor"
orphan = false
run = "hx %s"

[[opener.edit]]
block = false
desc = "Edit file with TextEdit"
orphan = true
run = "open -a TextEdit %s"

[[opener.play]]
block = false
desc = "Play media using MPV"
orphan = true
run = "mpv %s"

[[opener.play]]
block = false
desc = "Play media using Apple Music"
orphan = true
run = "open -a Music %s"

[[opener.play]]
block = false
desc = "Play media using IINA"
orphan = true
run = "iina %s"

[[opener.play]]
block = false
desc = "Play music using IINA"
orphan = true
run = "iina --music-mode %s"

[[opener.view]]
block = false
desc = "View PDF file in Skim"
orphan = true
run = "open -a Skim %s"

[preview]
max_height = 800
max_width = 800
tab_size = 2
wrap = "yes"
