[[language]]
name        = "html"
auto-format = false
indent      = { tab-width = 4, unit = "    " }

[[language]]
name             = "mojo"
file-types       = ["mojo"]
indent           = { tab-width = 4, unit = "    " }
language-servers = ["mojo-lsp-server"]

[[language]]
name   = "odin"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name        = "python"
auto-format = true
formatter   = { command = "ruff", args = ["format", "-"] }

[[language]]
name        = "ruby"
auto-format = true

[language.formatter]
args    = ["exec", "rubocop", "--stdin", "foo.rb", "-a", "--stderr", "--fail-level", "fatal"]
command = "bundle"

[[language]]
name        = "toml"
auto-format = true

[[language]]
name        = "zig"
auto-format = true

[language-server.mojo-lsp-server]
command = "mojo-lsp-server"
