[[language]]
name        = "html"
auto-format = false

[[language]]
name        = "markdown"
auto-format = true
formatter   = { command = "rumdl", args = ["fmt", "-", "--silent"] }

[[language]]
name        = "python"
auto-format = true

[[language]]
name             = "ruby"
auto-format      = true
language-servers = ["ruby-lsp"]

[[language]]
name        = "toml"
auto-format = true

[[language]]
name        = "zig"
auto-format = false

[language-server.ruby-lsp]
command = "ruby-lsp"
config  = { diagnostics = true, formatting = true }
