[[language]]
name        = "html"
auto-format = false

[[language]]
name        = "markdown"
auto-format = false

[language.formatter]
command = "rumdl"
args    = ["fmt", "-", "--silent"]

[[language]]
name        = "python"
auto-format = true

[[language]]
name        = "ruby"
auto-format = true

[[language]]
name        = "toml"
auto-format = true

[[language]]
name        = "zig"
auto-format = false
