[bootstrap.user]
login_shell = "/usr/local/bin/fish"

[env]
GOPATH = "{{env.HOME}}/Code/env/go"
HELIX_RUNTIME = "{{env.HOME}}/Code/rs/helix/runtime/"

[tools]
go = "latest"
ruby = "latest"
rust = "stable"
typst = "latest"
zig = "latest"
