complete -c nb -f
complete -c nb -n '__fish_use_subcommand' -a 'init' -d 'Create /opt/nanobrew/ directory tree'
complete -c nb -n '__fish_use_subcommand' -a 'install' -d 'Install packages'
complete -c nb -n '__fish_use_subcommand' -a 'remove' -d 'Uninstall packages'
complete -c nb -n '__fish_use_subcommand' -a 'reinstall' -d 'Reinstall packages'
complete -c nb -n '__fish_use_subcommand' -a 'list' -d 'List installed packages'
complete -c nb -n '__fish_use_subcommand' -a 'leaves' -d 'List packages with no dependents'
complete -c nb -n '__fish_use_subcommand' -a 'info' -d 'Show formula info'
complete -c nb -n '__fish_use_subcommand' -a 'search' -d 'Search for packages'
complete -c nb -n '__fish_use_subcommand' -a 'where' -d 'Find packages by pattern'
complete -c nb -n '__fish_use_subcommand' -a 'upgrade' -d 'Upgrade packages'
complete -c nb -n '__fish_use_subcommand' -a 'update' -d 'Self-update nanobrew'
complete -c nb -n '__fish_use_subcommand' -a 'update-registry' -d 'Refresh the verified-upstream registry'
complete -c nb -n '__fish_use_subcommand' -a 'doctor' -d 'Check installation health'
complete -c nb -n '__fish_use_subcommand' -a 'cleanup' -d 'Remove stale caches'
complete -c nb -n '__fish_use_subcommand' -a 'outdated' -d 'List outdated packages'
complete -c nb -n '__fish_use_subcommand' -a 'pin' -d 'Pin a package'
complete -c nb -n '__fish_use_subcommand' -a 'unpin' -d 'Unpin a package'
complete -c nb -n '__fish_use_subcommand' -a 'rollback' -d 'Rollback to previous version'
complete -c nb -n '__fish_use_subcommand' -a 'link' -d 'Link an installed keg into the prefix'
complete -c nb -n '__fish_use_subcommand' -a 'unlink' -d 'Remove an installed keg prefix links'
complete -c nb -n '__fish_use_subcommand' -a 'bundle' -d 'Export/import package lists'
complete -c nb -n '__fish_use_subcommand' -a 'deps' -d 'Show dependency tree'
complete -c nb -n '__fish_use_subcommand' -a 'services' -d 'Manage services'
complete -c nb -n '__fish_use_subcommand' -a 'completions' -d 'Generate shell completions'
complete -c nb -n '__fish_use_subcommand' -a 'telemetry' -d 'Manage anonymous download telemetry'
complete -c nb -n '__fish_use_subcommand' -a 'nuke' -d 'Completely uninstall nanobrew'
complete -c nb -n '__fish_use_subcommand' -a 'migrate' -d 'Import existing Homebrew packages'
complete -c nb -n '__fish_use_subcommand' -a 'help' -d 'Show help'
complete -c nb -n '__fish_seen_subcommand_from remove uninstall upgrade pin unpin rollback link unlink' -a '(nb list --names 2>/dev/null)'
complete -c nb -n '__fish_seen_subcommand_from install info' -l cask -d 'Cask mode'
complete -c nb -n '__fish_seen_subcommand_from install' -l deb -d 'Deb mode'
complete -c nb -n '__fish_seen_subcommand_from install' -l shims -d 'Use private dependency executable shims'
complete -c nb -n '__fish_seen_subcommand_from services' -a 'list start stop restart'
complete -c nb -n '__fish_seen_subcommand_from completions' -a 'zsh bash fish'
complete -c nb -n '__fish_seen_subcommand_from telemetry' -a 'status on off'
